name: uh
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  botton_nav_bar: ^1.0.2
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^5.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/
  #   - images/a_dot_ham.jpeg